### ISSUE TITLE
Why not make crazyflie-crtp-cpp a separate repository and add it as a submodule to this repo?

### ISSUE THREAD

**Issue by trakevital** [bitcraze/crazyflie-link-cpp#16]
I'm currently working with a college on a project with Crazyflies in which we were given the task of creating a c++ version of the crazyflie-lib-python repository which is what we have been doing for the last few months. You can checkout the repo [here](https://github.com/M-R-VulcaN/crazyflie-link-cpp-expanded). 

We started working on this project once we saw that you have created this repository whose purpose is linking the python lib with crtp implementations in c++ code in order to improve the library's performance. We decided to fork your repository to add more functionality to it (which seems now like it was a bad idea) especially functions dealing with Log, Param and AppChannel communication with the crazyflie.

We are close to finishing this project of ours but we don't want it to be detached from your project, so that in case you update your code our project will also receive the updates. To do this we are planning to add your repo as a submodule, however a little digging into the matter revealed that this is quite difficult because of the python bindings. 

I'm writing all this in part, to update you with what we are doing with the repo whose link I attached above, since we realised that it must look quite confusing (badly named and still in development). Nevertheless, the main reason I am writing this issue is because I would suggest to you to separate this repo into two repos, one being the "crazyflie-crtp-cpp" which is written in c++ which has nothing to do with python whatsoever but instead is the plain implementation of the crtp in c++ and the other which will include crazyflie-crtp-cpp as a submodule, which will add the py-bindings.

This would be very helpful to us, but it would probably help whoever in the future will be willing to adapt crazyflie-crtp-cpp for himself, to write his own crazyflie lib in c++, or for adding bindings for other languages like rust or what not.

I'm very eager to hear your response to what I have written, and am sorry in advance if it will take me long to respond to you like last time.

**Comment by whoenig** [comment]
Splitting it in two parts increases modularity, but also dramatically worsens maintainability. As an example, consider you are adding a new feature. In the current version, one can just have a single commit (or single PR), that includes the new feature in C++, updates the Python bindings, and adds a test (perhaps using the Python bindings, since that makes testing easier). If the repo is split, you need at least two commits (or PRs) to achieve the same and it becomes cumbersome to track related changes in the history.

For that reason, many projects actually including the Python bindings in their repos (e.g., OMPL, Drake). However, it is also common to disable the Python bindings by default or offer an option to disable it to avoid unnecessary dependencies. Would that solve your problem?

**Comment by trakevital** [comment]
Thanks for the quick answer, yes I think adding an option to disable the Python bindings would be very helpful, maybe add a [cmake module file](https://cmake.org/cmake/help/latest/command/include.html) which could then be included by us in our CMakeLists.txt file without the python bindings.

**Comment by whoenig** [comment]
Sounds good - I'll look into this (but PRs are also welcome). FYI, I started working on the crazyflie_cpp port at https://github.com/whoenig/crazyflie_cpp/tree/dev-crazyflie-link-cpp, which already uses this repo as a submodule (but with Python bindings still active). It might make sense to combine our efforts, depending on which features you have and what your goals are etc. For crazyflie_cpp the short-term goal is to stick with the current API as much as possible, to minimize required changes in the dependencies (crazyflie_ros and crazyswarm). Longer term, I also want to re-visit some of the API choices.

**Comment by trakevital** [comment]
I'm sure we'd be happy to help you with this, our goals currently are to write a c++ version of the python library to increase performance and get all the benefits that c++ gives over python, like better multi-threading.

We started working on this after the promising performance boost describe in [this blog](https://www.bitcraze.io/2021/02/communication-reliability/), we thought "If replacing the python crtp code with c++ code would increase performance so well, why not try replacing all the code with c++ and seeing if the performance increases even more?". Hoping for a performance boost was one of the main reasons that we started working on the crazyflie-lib-cpp.

While you're looking into adding the ability to disable the python bindings I'll discuss with my colleagues about your purposeful to help you out with what you're doing, and hopefully we'll get back to you soon. In the mean time I am quite certain they'd be happy to help.

**Comment by trakevital** [comment]
OK, we can move the higher level code into a "cflib" folder , like in the python version. and then we will do a PR back into crazyflie-link-cpp. Is that  acceptable?

**Comment by whoenig** [comment]
There should be no higher-level code in crazyflie-link-cpp - this repository is for link-related code only. As discussed earlier, you can use this as a submodule in another project (e.g., crazyflie-lib-cpp if you want to follow the bitcraze naming convention). I am doing the same with crazyflie_cpp and I am happy to help with any issues regarding that.

By the way, crazyflie_cpp has been around for at least 5 years and is written in C++. From what I can tell so far, it mostly had performance benefits because of the link layer being implemented natively. I don't expect very big performance otherwise, unless you operate a swarm (a use-case the Crazyswarm at https://crazyswarm.readthedocs.io/en/latest/ has been optimized for, which also relies on crazyflie_cpp under the hood).

**Comment by whoenig** [comment]
@trakevital Let me know if this change is acceptable for your use-case, so we can close this issue. You may find an example usage at https://github.com/whoenig/crazyflie_cpp/blob/dev-crazyflie-link-cpp/CMakeLists.txt#L11-L13.

**Comment by trakevital** [comment]
I'll start checking right away hopefully will answer you in the next 24 hours

**Comment by trakevital** [comment]
I am right now checking the tweak you've made and I run into this error when trying to `make` the files.
```
class "bitcraze::crazyflieLinkCpp::Packet" has no member "payloadAtString"C/C++(135)
‘const class bitcraze::crazyflieLinkCpp::Packet’ has no member named ‘payloadAtString’
```

```
crazyflie_cpp/src/crtp.cpp: In static member function ‘static std::string crtpConsoleResponse::text(const bitcraze::crazyflieLinkCpp::Packet&)’:
crazyflie_cpp/src/crtp.cpp:78:12: error: ‘const class bitcraze::crazyflieLinkCpp::Packet’ has no member named ‘payloadAtString’
```

**Comment by whoenig** [comment]
You would need to try an [older commit](https://github.com/whoenig/crazyflie_cpp/commit/f73b0342057d902375227c3a8ca3a47ed2bc9a52), since I made some changes in crazyflie-link-cpp that are not pull-requested, yet. This should be independent of of this issue, though.

**Comment by trakevital** [comment]
Yep it worked. Only one last thing: I recommend changing the crazyflie-link-cpp submodule url from: `git@github.com:bitcraze/crazyflie-link-cpp.git` to: `https://github.com/bitcraze/crazyflie-link-cpp.git` as described in [here] (https://stackoverflow.com/a/14807969/13093413)

**Comment by whoenig** [comment]
Thanks! I'll also need to set up CI, which should be able to find those sort of problems.
